[package]
name = "fix_akonadi"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.6", features = [ "mysql", "runtime-tokio-native-tls", "macros" ] }
tokio = { version = "1", features = [ "full" ] }
