[project]
name = "fix-local-mail"
version = "1.0.0"
description = "Akonadi database fix tool for local mails"
requires-python = ">=3.10"
dependencies = [
    "pre-commit>=4.5.1",
]

[tool.uv]
python-version = "3.11"
